### ISSUE TITLE
Dashboards.addDataSource(name, obj, force) is not function

### ISSUE THREAD

**Issue by abhisheksrivastava001** [webdetails/cdf#912]
I was trying to add a new datasource in CDE through script using the mentioned code snippet -
`// defaults to a CDA query`
`dashboard.addDataSource("myDatasource", {dataAccessId: "query1", path: "/public/queries.cda"});`
`dashboard.getQuery({dataSource: "myDatasource"});`

Though I found this error on console
![image](https://cloud.githubusercontent.com/assets/23656955/23458949/24417586-fe76-11e6-9902-7a0dd538386a.png)

Reference in the link - https://help.pentaho.com/Documentation/6.1/0R0/cdf.dashboard.Dashboard#addDataSource

![image](https://cloud.githubusercontent.com/assets/23656955/23458838/c5093d10-fe75-11e6-86b8-78856ec1fbfb.png)

Do we have any workaround in this case? 
Awaiting quick response and TIA.

**Comment by pamval** [comment]
what version are you on and are you using require.js dashboards or legacy ones?

**Comment by abhisheksrivastava001** [comment]
I am using version 6.1.0.1.196
Its just default one, I am not using RequireJS in the dashboard.

**Comment by pamval** [comment]
That documentation is specific to the require.js API. Try enabling the require.js support in the settings panel for the dashboard (there's a checkbox)

**Comment by abhisheksrivastava001** [comment]
Thats working now. I can see console logs for loading require js and other files.
but **`Dashboards`** Object is undefined
![image](https://cloud.githubusercontent.com/assets/23656955/23469454/8ad47cec-fe9b-11e6-902f-7edc2969790b.png)

Any Idea ?

**Comment by pamval** [comment]
yeah, the Dashboards object does not exist in require.js. Refer to this documentation, please:

http://redmine.webdetails.org/projects/cde/wiki/RequireJS
http://redmine.webdetails.org/projects/cdf/wiki/RequireJS

**Comment by abhisheksrivastava001** [comment]
It works fine now. :+1: 
Thank you for your help and guidance !
